version: '3.8'

services:
    app:
        build: .
        container_name: app
        #entrypoint: ./.docker/app/entrypoint.sh
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
          - db
          - redis
        #environment:
        #  - DB_HOST=db
        #  - DB_DATABASE=laravel
        #  - DB_USERNAME=root
        #  - DB_PASSWORD=root
        #  - REDIS_HOST=redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        #entrypoint: ./.docker/nginx/entrypoint.sh
        restart: always
        tty: true
        ports:
          - "8000:80"
        volumes:
          - .:/var/www
        networks:
          - app-network
        depends_on:
          - app
        environment:
          - APP_HOST=app
          - APP_PORT=9000

    db:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            # - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
